global:
  scrape_interval:     15s

scrape_configs:
  - job_name: "attendance_metrics"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["host.docker.internal:8000"]

rule_files:
  - 'alert-rules.yml'
alerting:
  alertmanagers:
    - scheme: http
    - static_configs:
        - targets: ['host.docker.internal:9093']
