FROM grafana/grafana:10.1.5

##################################################################
## CONFIGURATION
##################################################################

## Set Grafana options
ENV GF_ENABLE_GZIP=true
ENV GF_USERS_DEFAULT_THEME=dark

## Enable Anonymous Authentication
#ENV GF_AUTH_ANONYMOUS_ENABLED=true
ENV GF_AUTH_BASIC_ENABLED=false

## Disable Sanitize
ENV GF_PANELS_DISABLE_SANITIZE_HTML=true

## Disable Explore
ENV GF_EXPLORE_ENABLED=false

# Updates Check
ENV GF_ANALYTICS_CHECK_FOR_UPDATES=false
ENV GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES=false

##################################################################
## COPY ARTIFACTS
## Required for the App plugin
##################################################################

#COPY --chown=grafana:root dist /app
COPY entrypoint.sh /

##################################################################
## Customization depends on the Grafana version
## May work or not work for the version different from the current
##################################################################
USER root

##################################################################
## VISUAL
##################################################################

## Replace Favicon and Apple Touch
COPY images/fav32.png /usr/share/grafana/public/img
COPY images/fav32.png /usr/share/grafana/public/img/apple-touch-icon.png

## Replace Logo
COPY images/grafana_icon.svg /usr/share/grafana/public/img/grafana_icon.svg

## Update Background
COPY images/g8_login_dark.svg /usr/share/grafana/public/img/g8_login_dark.svg
COPY images/g8_login_dark.svg /usr/share/grafana/public/img/g8_login_light.svg

# Adding prometheus as a data source
COPY prometheus-provisioning.yaml /etc/grafana/provisioning/datasources

# Adding the config for the dasboards
COPY dashboards-provisioning.yaml /etc/grafana/provisioning/dashboards

# Adding the dashboards
COPY dashboards /etc/grafana/provisioning/dashboards


##################################################################
## HANDS-ON
##################################################################

# Set Home Page To Be The Dashboards Page
RUN sed -i 's|home_page =|home_page = /dashboards/|' /usr/share/grafana/conf/defaults.ini

# Adding Prometheus As A Data Source
COPY prometheus-provisioning.yaml /etc/grafana/provisioning/datasources

# Adding The Config For The Dasboards
COPY dashboards-provisioning.yaml /etc/grafana/provisioning/dashboards

# Update Title
RUN sed -i 's|<title>\[\[.AppTitle\]\]</title>|<title>Attendance Tracker</title>|g' /usr/share/grafana/public/views/index.html

# Update Help menu
RUN sed -i "s|\[\[.NavTree\]\],|nav,|g; \
    s|window.grafanaBootData = {| \
    let nav = [[.NavTree]]; \
    const alerting = nav.find((element) => element.id === 'alerting'); \
    if (alerting) { alerting['url'] = '/alerting/list'; } \
    const dashboards = nav.find((element) => element.id === 'dashboards/browse'); \
    if (dashboards) { dashboards['children'] = [];} \
    const connections = nav.find((element) => element.id === 'connections'); \
    if (connections) { connections['url'] = '/datasources'; connections['children'].shift(); } \
    const help = nav.find((element) => element.id === 'help'); \
    if (help) { help['subTitle'] = 'Grafana OSS'; help['children'] = [];} \
    window.grafanaBootData = {|g" \
    /usr/share/grafana/public/views/index.html

# Update Title
RUN find /usr/share/grafana/public/build/ -name *.js -exec sed -i 's|AppTitle="Grafana"|AppTitle="Attendance Monitoring"|g' {} \;

## Update Login Title
RUN find /usr/share/grafana/public/build/ -name *.js -exec sed -i 's|LoginTitle="Welcome to Grafana"|LoginTitle="Welcome to Attendance Monitoring"|g' {} \;

## Remove Documentation, Support, Community in the Footer
RUN find /usr/share/grafana/public/build/ -name *.js -exec sed -i 's|\[{target:"_blank",id:"documentation".*grafana_footer"}\]|\[\]|g' {} \;
#
## Remove Edition in the Footer
RUN find /usr/share/grafana/public/build/ -name *.js -exec sed -i 's|({target:"_blank",id:"license",.*licenseUrl})|()|g' {} \;

## Remove Version in the Footer
RUN find /usr/share/grafana/public/build/ -name *.js -exec sed -i 's|({target:"_blank",id:"version",.*CHANGELOG.md":void 0})|()|g' {} \;

## Remove New Version is available in the Footer
RUN find /usr/share/grafana/public/build/ -name *.js -exec sed -i 's|({target:"_blank",id:"updateVersion",.*grafana_footer"})|()|g' {} \;

## Remove News icon
RUN find /usr/share/grafana/public/build/ -name *.js -exec sed -i 's|..createElement(....,{className:.,onClick:.,iconOnly:!0,icon:"rss","aria-label":"News"})|null|g' {} \;

## Remove Open Source icon
RUN find /usr/share/grafana/public/build/ -name *.js -exec sed -i 's|.push({target:"_blank",id:"version",text:`${..edition}${.}`,url:..licenseUrl,icon:"external-link-alt"})||g' {} \;

USER grafana

## Entrypoint
ENTRYPOINT [ "/bin/bash", "/entrypoint.sh" ]
